# -*- coding: utf-8 -*-
"""hmwrk5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zgc0bGcd0GYi1iMgBJe8jJDSSPMHFEGG
"""

#1 
hour = int(input("Enter hour: "))
period = str(input("Enter period: am or pm: "))
time_dif = int(input("How many hours ahead? "))
if (hour + time_dif) < 12:
  if period == 'am':
    period = 'am'
  elif period == 'pm':
    period = 'pm'
  print ("New hour: ", (hour + time_dif), period)
else:
    if period == 'am':
        period = 'pm'
    elif period == 'pm':
        period = 'am'
    print ("New hour: ", (hour + time_dif - 12 ), period)


#2
import random
Questions = {
    1: "Question1",
    2: "Question2",
    3: "Question3",
    4: "Question4",
    5: "Question5",
    6: "Question6",
    7: "Question7",
    8: "Question8",
    9: "Question9",
    10: "Question10",
}
Answers = ["Answer1","Answer2", "Answer3", "Answer4", "Answer5", "Answer6", "Answer7", "Answer8", "Answer9", "Answer10" ]
count = 0
for i in range (4):
    Q_number = (random.randint(1,10))
    print (Questions[Q_number])
    User_Answer=str(input("Your answer: "))
    if User_Answer == Answers[Q_number-1]:
        count += 1

print ("Percentage of correct answers is: ", count/4*100,"%")
    

#3


#4